### ISSUE TITLE
如何增加自定义扩充字？

### ISSUE THREAD

**Issue by jostyee** [placeless/squirrel_config#12]
比如在 placeless_punct.dict.yaml 里增加一行
```
菓 go  1
```

重新部署后输入go候选字列表里面没有菓字，是还需要做什么操作吗？

**Comment by placeless** [comment]
可以放到那里，部署未生效，可能是你没有用 tab 分隔。

`placeless_punct.dict.yaml` 原意是放置一些额外的标记，其他的自定义字典，按照规格做好，挂到 `extended.dict.yaml` 里边即可。

**Comment by jostyee** [comment]
谢谢，果然还是tab的问题，用Sublime Text编辑的时候自动转成了空格没主意。
